### PR TITLE
revision cleanup + prevention of new ones 

### PR DESCRIPTION
**Pull request by mollux**
## Summary

this PR addresses the huge amounts of obsolete revisions of blog items by
* cleaning them up in an update hook
* setting the change dates correct, so they are relevant change date of the revision
* preventing a new revision is created every time a blog item is rendered (which is on production worst case every 15 minutes).

As this PR is a blocker for a smoother dev experience (no need to downsync and import a db of 6GB), we (Dropsolid) will merge and deploy this change via the Dropsolid Platform.

Afterwards, following PR's can follow the normal flow with the different QA envs.

## How to test

The update hook has run on the dev env (https://mauticorg.dev.sites.dropsolid-sites.com/), with a database dump of 29/08

* login to the dev (blocked by #20)
* verify the list fo blog items is correct
* verify the list of revisions of blog items is correct
* verify you can still add blog items (TO DOUBLE CHECK, AS THIS WILL POTENTIALLY SYNC TO DISCOURSE)

### content overview list

relevant changed dates

* **before**
Screenshot 2023-08-30 at 15 02 42

* **after**
Screenshot 2023-08-30 at 15 02 55

Next to that, this also solves a performance issue (manually mitigated on production).
On every revision save, the cachetags for the node are invalidated.
In case of the blog content type, this is `node_list` and `node_list:blog`.
As a list of blog items is shown on every page, this literally means that the whole site is only cacheable for a few seconds.

### revision list

relevant revisions

* **before**
Screenshot 2023-08-30 at 15 06 46

* **after**
Screenshot 2023-08-30 at 15 06 58

## Metadata

| Question | Answer |
|----------|--------|
| Did you use a meaningful pull request title? | **yes**/no
| Did you apply meaningful labels to the pull request? | yes/no
| Did you perform a self review first? | **yes**/no
| Documentation reflects changes? | yes/**no**
| `CHANGELOG` reflects changes? | yes/**no**
| Unit/Functional tests reflect changes? | yes/**no**
| Did you perform browser testing? | yes/**no**
| Risk level | Low, **Medium**, High
| Relevant links | #19

### CODE REVIEW

**Comment by mollux** [comment]
QA blocked on #20

**Review by RCheesley — APPROVED** [review]
Able to create new blog post: https://mauticorg.dev.sites.dropsolid-sites.com/blog/community/test-new-blog (in draft)

Revisions are as I would expect - checked several articles.

Sorting by updated date actually works for the first time in ages! 🚀 

Thanks!

**Comment by RCheesley** [comment]
Sounds good @nick-vanpraet - is there any chance we can schedule it to run over a weekend or something? I think that would inconvenience the least folks if we are expecting the site to be in maintenance mode. Unless there is some way to run it in dev and then up-sync to prod without the downtime?

**Comment by nick-vanpraet** [comment]
It shouldn't be necessary to run it in maintenance mode, but running it during the weekend is safest regardless.

**Comment by mollux** [comment]
This has been rolled out on production, and all went well.
Database is overall more than 40 times smaller, and e.g. the `node_revision__body` shrank from 6.9GB to 18MB(!)

**Comment by RCheesley** [comment]
Thanks so much folks, great to have this sorted out so that we can now start with development properly.

Is there anything left outstanding, I noticed that the mirroring task seems to be failing?

**Comment by nick-vanpraet** [comment]
Yeah, mirroring on the "PR" event doesn't work so I disabled that. I think we can remove the update hook as Mattias ran it as a stand alone script, then we can merge this PR.

@mollux is this correct?

**Comment by RCheesley** [comment]
Would be super to get this merged so that we can unblock the development work!

**Comment by mollux** [comment]
@nick-vanpraet indeed, let me change that so we can merge

**Pull request merged**
