### PR TITLE
Create funding-manifest-urls

### PR DESCRIPTION
**Pull request by RCheesley**
## Summary
In applying for the funding from the FLOSS fund, creating the funding.json file requires us to link to https://github.com/mautic/mautic/blob/5.x/funding.json in a funding manifest file on the .well-known directory of any sites we're linking out to.

This PR should add that directory and file, per the instructions here: https://floss.fund/funding-manifest/
## Metadata

| Question | Answer |
|----------|--------|
| Did you use a meaningful pull request title? | yes
| Did you apply meaningful labels to the pull request? | yes
| Did you perform a self review first? | yes
| Documentation reflects changes? | N/A
| `CHANGELOG` reflects changes? | N/A
| Unit/Functional tests reflect changes? | N/A
| Did you perform browser testing? | N/A
| Risk level | Low
| Relevant links | N/A

### CODE REVIEW

**Comment by RCheesley** [comment]
Looks like there's a bug with the GitLab mirroring here.

**Review by nick-vanpraet — APPROVED** [review]
Deployed to QA1, file shows up correctly. Looks good to merge.

**Comment by RCheesley** [comment]
Thanks @nick-vanpraet - merged!

**Comment by RCheesley** [comment]
@nick-vanpraet I think it should now show at https://www.mautic.org/.well-known/funding-manifest-urls but it seems there's a 404 on that page. Does it take a time to deploy, maybe?

**Comment by nick-vanpraet** [comment]
Merging into main does not trigger a build iirc, only QA labels do. You'll have to log in to platform to manually trigger a build.

**Comment by RCheesley** [comment]
OK so I just deploy from QA1 -> Prod?

**Comment by nick-vanpraet** [comment]
No just log in to platform, navigate to the live environment, hit deploy and enter the branch to deploy, so main.

https://support.dropsolid.io/devops/environments/shortcuts/deploy

**Pull request merged**
